# Site Settings
locale                   : "en-US"
title                    : "Ryan K. Waples"
title_separator          : "-"
name                     : &name "Ryan K. Waples"
description              : &description "Academic website for Ryan K. Waples"
url                      : https://rwaples.github.io
baseurl                  : ""
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"


email: ryan.waples@gmail.com
twitter_username: waplesryan
github_username:  rwaples

show_downloads: false
analytics :
  provider : false
sharing :
  provider : false
comments :
  provider : false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
theme: jekyll-theme-cayman
