title: [Ryan Waples]
description: "Personal website for Ryan K. Waples"
show_downloads: false

header-img: img/Banner0.jpg
baseurl: ""

email: ryan.waples@gmail.com
twitter_username: waplesryan
github_username:  rwaples

url: "http://rwaples.github.io"
baseurl: ""


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

theme: jekyll-theme-cayman